books/urls.py
from django.urls import path
from .views import landing

urlpatterns = [
    path('', landing, name='landing'),
]

goodreads/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('books.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'), name='users'),

]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
]

books/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)

    def __str__(self):
        return self.title
    

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} | {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"


class BookReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )

    def __str__(self):
        return f"{self.stars_given} stars for {self.book.title} by {self.user.username}"

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms


class UserCreateForm(forms.Form):

    username = forms.Form()

books/views.py
from django.shortcuts import render


def landing(request):
    return render(request, 'landing.html')

users/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View


class RegisterView(View):

    @staticmethod
    def get(request):
        return render(request, 'users/register.html')

    @staticmethod
    def post(request):
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']

        user = User.objects.create(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email
        )
        user.set_password(password)
        user.save()

        return redirect("users:login")


class LoginView(View):

    @staticmethod
    def get(request):
        return render(request, 'users/login.html')

templates/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>Welcome GOODREAD WEBSITE</h3>
    <div>
        <p>
            <a href="{% url 'users:login' %}">Login</a> /
            <a href="{% url 'users:register' %}">Register</a>
        </p>
    </div>





</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

    <h1>Login page</h1>

</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>

    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" id="username"> <br> <br>

        <label for="first_name">First name:</label>
        <input type="text" name="first_name" id="first_name"><br> <br>

        <label for="last_name">Last name:</label>
        <input type="text" name="last_name" id="last_name"><br> <br>

        <label for="email">Emal:</label>
        <input type="email" name="email" id="email"><br> <br>

        <label for="password">Password:</label>
        <input type="password" name="password" id="password"><br> <br>

        <button type="submit">Submit</button>
    </form>
</body>
</html>